# Generated by Django 4.2 on 2024-09-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditrequest",
            name="seller_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_request",
                to="charge.sellerprofile",
            ),
        ),
    ]
