# Generated by Django 4.2 on 2024-09-02 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0003_alter_creditrequest_seller_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="inventory",
            field=models.PositiveBigIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
