# Generated by Django 4.2 on 2024-09-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0004_phonenumber_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="phone_number",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="phone_transaction",
                to="charge.phonenumber",
            ),
        ),
    ]
