version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_DB=charge_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nima7898
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: charge_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nima7898
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A charge_hub_project worker --pool=prefork --loglevel=INFO -E
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A charge_hub_project beat --loglevel=INFO
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - web

volumes:
  postgres_data:
