# Generated by Django 4.2 on 2024-09-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charge", "0005_alter_transaction_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditrequest",
            name="previously_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("succeeded", "succeeded"),
                    ("failed", "failed"),
                    ("pending", "pending"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
